{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "93616baa_bc507de0",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 16
      },
      "lineNbr": 0,
      "author": {
        "id": 24824
      },
      "writtenOn": "2022-09-06T14:28:20Z",
      "side": 1,
      "message": "Extra changes in 15 got in by accident during rebasing. Removed them in 16 so this diff is what was intended:\n\nhttps://review.opendev.org/c/x/charm-ovn-central/+/847506/14..16/src/wheelhouse.txt",
      "revId": "2af5cf4dbd11d5ec6a6bb6a71faf019d2538de5f",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "fa112f11_a43ec8e9",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 16
      },
      "lineNbr": 0,
      "author": {
        "id": 24824
      },
      "writtenOn": "2022-09-06T16:23:05Z",
      "side": 1,
      "message": "This time a vault unit is in the error state:\n\n2022-09-06 15:08:51.517969 | focal-medium | zaza.model.UnitError: Units vault/0 in error state\n",
      "revId": "2af5cf4dbd11d5ec6a6bb6a71faf019d2538de5f",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "c97743e4_1d95a1b4",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 16
      },
      "lineNbr": 0,
      "author": {
        "id": 24824
      },
      "writtenOn": "2022-09-06T18:34:36Z",
      "side": 1,
      "message": "https://paste.opendev.org/show/bhB6k9hvp3KpBeAsQJqu/\n\n2022-09-06 15:08:22 WARNING unit.vault/0.shared-db-relation-changed logger.go:60     raise exceptions.InternalServerError(\n2022-09-06 15:08:22 WARNING unit.vault/0.shared-db-relation-changed logger.go:60 hvac.exceptions.InternalServerError: core: barrier reports initialized but no seal configuration found, on get http://127.0.0.1:8220/v1/sys/seal-status\n2022-09-06 15:08:22 ERROR juju.worker.uniter.operation runhook.go:140 hook \"shared-db-relation-changed\" (via explicit, bespoke hook script) failed: exit status 1",
      "revId": "2af5cf4dbd11d5ec6a6bb6a71faf019d2538de5f",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "034e8723_7e241a16",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 16
      },
      "lineNbr": 0,
      "author": {
        "id": 24824
      },
      "writtenOn": "2022-09-06T18:34:43Z",
      "side": 1,
      "message": "recheck",
      "revId": "2af5cf4dbd11d5ec6a6bb6a71faf019d2538de5f",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "c03bac42_d3b4de03",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 16
      },
      "lineNbr": 0,
      "author": {
        "id": 24824
      },
      "writtenOn": "2022-09-06T20:19:49Z",
      "side": 1,
      "message": "2022-09-06 19:16:09.517849 | focal-medium | requests.exceptions.ConnectionError: (\u0027Connection aborted.\u0027, RemoteDisconnected(\u0027Remote end closed connection without response\u0027))\n",
      "revId": "2af5cf4dbd11d5ec6a6bb6a71faf019d2538de5f",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "47ae1deb_8c31b311",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 16
      },
      "lineNbr": 0,
      "author": {
        "id": 24824
      },
      "writtenOn": "2022-09-06T20:19:54Z",
      "side": 1,
      "message": "recheck",
      "revId": "2af5cf4dbd11d5ec6a6bb6a71faf019d2538de5f",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "ef9daf1f_b8eb5e5d",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 16
      },
      "lineNbr": 0,
      "author": {
        "id": 24824
      },
      "writtenOn": "2022-09-06T21:47:05Z",
      "side": 1,
      "message": "Now the problem is in the lack of a release pair \"jammy_zed\": https://github.com/openstack-charmers/zaza-openstack-tests/blob/a53ad38e755c8ab24c399096abe49285f46ea050/zaza/openstack/utilities/os_versions.py#L70-L82\n\n---\n\n2022-09-06 21:11:01.326406 | focal-medium | 2022-09-06 21:11:01 [INFO] looking at application: {\u0027name\u0027: \u0027ovn-central\u0027, \u0027type\u0027: {\u0027pkg\u0027: \u0027ovn-common\u0027, \u0027origin_setting\u0027: \u0027source\u0027}}\n2022-09-06 21:11:06.277562 | focal-medium | 2022-09-06 21:11:06 [INFO] ERROR\n2022-09-06 21:11:06.278104 | focal-medium | 2022-09-06 21:11:06 [INFO] \u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\n2022-09-06 21:11:06.278403 | focal-medium | 2022-09-06 21:11:06 [INFO] ERROR: setUpClass (zaza.openstack.charm_tests.ovn.tests.CentralCharmOperationTest)\n2022-09-06 21:11:06.278629 | focal-medium | 2022-09-06 21:11:06 [INFO] ----------------------------------------------------------------------\n2022-09-06 21:11:06.278860 | focal-medium | 2022-09-06 21:11:06 [INFO] Traceback (most recent call last):\n2022-09-06 21:11:06.279134 | focal-medium | 2022-09-06 21:11:06 [INFO]   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-central/src/.tox/func-target/lib/python3.8/site-packages/zaza/openstack/utilities/openstack.py\", line 1955, in get_os_release\n2022-09-06 21:11:06.279367 | focal-medium | 2022-09-06 21:11:06 [INFO]     index \u003d OPENSTACK_RELEASES_PAIRS.index(release_pair)\n2022-09-06 21:11:06.279574 | focal-medium | 2022-09-06 21:11:06 [INFO] ValueError: \u0027jammy_zed\u0027 is not in list\n2022-09-06 21:11:06.279779 | focal-medium | 2022-09-06 21:11:06 [INFO] During handling of the above exception, another exception occurred:\n2022-09-06 21:11:06.279967 | focal-medium | 2022-09-06 21:11:06 [INFO] Traceback (most recent call last):\n2022-09-06 21:11:06.280170 | focal-medium | 2022-09-06 21:11:06 [INFO]   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-central/src/.tox/func-target/lib/python3.8/site-packages/zaza/openstack/charm_tests/ovn/tests.py\", line 90, in setUpClass\n2022-09-06 21:11:06.280382 | focal-medium | 2022-09-06 21:11:06 [INFO]     super(CentralCharmOperationTest, cls).setUpClass()\n2022-09-06 21:11:06.280591 | focal-medium | 2022-09-06 21:11:06 [INFO]   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-central/src/.tox/func-target/lib/python3.8/site-packages/zaza/openstack/charm_tests/ovn/tests.py\", line 44, in setUpClass\n2022-09-06 21:11:06.280789 | focal-medium | 2022-09-06 21:11:06 [INFO]     cls.current_release \u003d openstack_utils.get_os_release(\n2022-09-06 21:11:06.280976 | focal-medium | 2022-09-06 21:11:06 [INFO]   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-central/src/.tox/func-target/lib/python3.8/site-packages/zaza/openstack/utilities/openstack.py\", line 1961, in get_os_release\n2022-09-06 21:11:06.281164 | focal-medium | 2022-09-06 21:11:06 [INFO]     raise exceptions.ReleasePairNotFound(msg)\n2022-09-06 21:11:06.281390 | focal-medium | 2022-09-06 21:11:06 [INFO] zaza.openstack.utilities.exceptions.ReleasePairNotFound: Release pair: jammy_zed not found in [\u0027trusty_icehouse\u0027, \u0027trusty_kilo\u0027, \u0027trusty_liberty\u0027, \u0027trusty_mitaka\u0027, \u0027xenial_mitaka\u0027, \u0027xenial_newton\u0027, \u0027yakkety_newton\u0027, \u0027xenial_ocata\u0027, \u0027zesty_ocata\u0027, \u0027xenial_pike\u0027, \u0027artful_pike\u0027, \u0027xenial_queens\u0027, \u0027bionic_queens\u0027, \u0027bionic_rocky\u0027, \u0027cosmic_rocky\u0027, \u0027bionic_stein\u0027, \u0027disco_stein\u0027, \u0027bionic_train\u0027, \u0027eoan_train\u0027, \u0027bionic_ussuri\u0027, \u0027focal_ussuri\u0027, \u0027focal_victoria\u0027, \u0027groovy_victoria\u0027, \u0027focal_wallaby\u0027, \u0027hirsute_wallaby\u0027, \u0027focal_xena\u0027, \u0027impish_xena\u0027, \u0027focal_yoga\u0027, \u0027jammy_yoga\u0027]\n",
      "revId": "2af5cf4dbd11d5ec6a6bb6a71faf019d2538de5f",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}